version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${HS_SERVER_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${HS_SERVER_DATASOURCE_PASSWORD}
    ports:
      - "${HS_SERVER_DATASOURCE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - postgres
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${HS_SERVER_DATASOURCE_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${HS_SERVER_DATASOURCE_PASSWORD}
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/${HS_SERVER_DATASOURCE_DATABASE}
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update

volumes:
  postgres-data:
