spring:
  datasource:
    url: jdbc:postgresql://${HS_SERVER_DATASOURCE_HOST}:${HS_SERVER_DATASOURCE_PORT}/${HS_SERVER_DATASOURCE_DATABASE}
    username: ${HS_SERVER_DATASOURCE_USERNAME}
    password: ${HS_SERVER_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    # disable-swagger-default-url: true
    path: "/swagger-ui"
    # operationsSorter : method

hs-server:
  security:
    jwt:
      secret-key: ${HS_SERVER_JWT_SECRET_KEY}
      expiration: ${HS_SERVER_JWT_EXPIRATION}
      refresh-expiration: ${HS_SERVER_JWT_REFRESH_EXPIRATION}

server:
  port: ${HS_SERVER_PORT}
